# Generated by Django 5.0.1 on 2024-01-26 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=32)),
                ('isim', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['isim'],
            },
        ),
        migrations.RenameField(
            model_name='uye',
            old_name='isim_soyisim',
            new_name='isim',
        ),
        migrations.AddField(
            model_name='uye',
            name='soyisim',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uye',
            name='tc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=1024)),
                ('kod', models.CharField(max_length=32)),
                ('yurtici_kod', models.CharField(max_length=32)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.il')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['isim'],
            },
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=1024)),
                ('kod', models.CharField(max_length=32)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.ilce')),
            ],
            options={
                'verbose_name': 'Mahalle',
                'verbose_name_plural': 'Mahalleler',
                'ordering': ['isim'],
            },
        ),
        migrations.CreateModel(
            name='UyeAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('isim', models.CharField(max_length=1024)),
                ('adres', models.TextField()),
                ('posta_kodu', models.CharField(blank=True, max_length=16)),
                ('tel', models.CharField(max_length=255)),
                ('gsm', models.CharField(max_length=255)),
                ('faks', models.CharField(blank=True, max_length=255)),
                ('firma', models.CharField(blank=True, max_length=1024)),
                ('vergi_dairesi', models.CharField(blank=True, max_length=1024)),
                ('vergi_no', models.CharField(blank=True, max_length=1024)),
                ('tip', models.CharField(blank=True, choices=[('B', 'Bireysel'), ('K', 'Kurumsal')], default='B', max_length=1)),
                ('adres_tipi', models.CharField(blank=True, choices=[('T', 'Teslimat'), ('F', 'Fatura')], default='T', max_length=1)),
                ('silindi', models.BooleanField(default=False)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.il')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.ilce')),
                ('mahalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.mahalle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Adresi',
                'verbose_name_plural': 'Kullanıcı Adresleri',
            },
        ),
    ]
