# Generated by Django 5.0.1 on 2024-01-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_il_rename_isim_soyisim_uye_isim_uye_soyisim_uye_tc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyeadresi',
            name='gsm',
        ),
    ]
