# Generated by Django 5.0 on 2024-03-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_sessiontokens_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontokens',
            name='payment_amount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
