# Generated by Django 5.0 on 2024-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_sessiontokens_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackHashTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_oid', models.CharField(max_length=200)),
                ('merchant_salt', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=200)),
                ('hash_value', models.CharField(max_length=400)),
                ('hash', models.CharField(max_length=400)),
            ],
        ),
    ]
