# Generated by Django 5.0 on 2024-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_callbackhashtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontokens',
            name='params_to_send',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
