# Generated by Django 5.0 on 2024-03-24 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_sessiontokens_params_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackhashtokens',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontokens',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
