# Generated by Django 5.0 on 2024-01-13 20:17

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=30)),
                ('aktif', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=25, verbose_name='İSİM')),
                ('kod', models.CharField(blank=True, max_length=4, null=True)),
                ('aciklama', models.CharField(blank=True, max_length=124)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resim', models.ImageField(default='products/default_product_image.jpg', upload_to='products/%Y/%m/%d/')),
                ('aktif', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.kategori')),
            ],
            options={
                'verbose_name': 'Urun',
                'verbose_name_plural': 'Urunler(Urunlar)',
                'ordering': ['-aktif', 'isim'],
            },
        ),
    ]
