# Generated by Django 5.0 on 2023-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.ImageField(default='products/default_product_image.jpg', upload_to='products/%Y/%m/%d/'),
        ),
    ]
