# Generated by Django 5.0 on 2024-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stok_durumu',
            field=models.IntegerField(default=0),
        ),
    ]
