# Generated by Django 5.0 on 2024-01-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_kategori_sira'),
        ('pages', '0002_urun_stok_durumu'),
    ]

    operations = [
    ]
