# Generated by Django 5.0 on 2023-12-23 22:16

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=imagekit.models.fields.ProcessedImageField(default='products/default_product_image.jpg', upload_to='products/%Y/%m/%d/'),
        ),
    ]
