# Generated by Django 5.0 on 2023-12-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.ImageField(default='products/default_product_image.jpg', upload_to='products/%Y/%m/%d/'),
        ),
    ]
