# Generated by Django 5.0.1 on 2024-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=255, verbose_name='İSİM'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kod',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
