# Generated by Django 5.0 on 2024-01-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_kategori_urun_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.kategori'),
        ),
    ]
