# Generated by Django 5.0 on 2024-01-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparissatiri',
            name='sinif_ismi',
        ),
    ]
