# Generated by Django 5.0.1 on 2024-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0002_remove_siparissatiri_sinif_ismi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepetsatiri',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
